version: "3"

services:
  webapp:
    build: .
    #image: rodneydav/big4trendanalysis:2.0
    #volumes:
    #  - .:/var/www/html
    ports:
      - 3000:5000
    networks:
      - default
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure

        version: "3"

